### PR TITLE
Fixed laser not rendering on ship and raytrece rendering pass through block

### PR DESCRIPTION
**Pull request by Sunspot0411**
Hi Keridos, I just find an issue with laser not rendering on VS ship and got it fixed. I also fixed raytracing rendering through blocks when blocks get hits by raytracing turrets. Also by the way can you make an curseforge update for 3.1.x Valkyrien Skies compatible version?

### CODE REVIEW

**Comment by Keridos** [comment]
Eh i am sure that currently stuff is broken, I just noticed your last pull only added laser turrets. so probably rail guns are not working properly, also you made it so that accuracy upgrades do not work anymore in laser turrets. Gonna test this, guessing this might break laser turrets even more

Edit: after testing: good work on the check for range of blockhits. that fixes rendering. Won't merge this though, fixed the bugs you introduced last pull request.  The issue with lasers btw was that you apparently made the rendering use coordinates that were 2x transformed on ships.

With the commit I do (will reference this PR) prolly VW ships with lasers and railguns should work properly.

**Comment by Sunspot0411** [comment]
@Keridos I checked before made this commit, 2x transform bad code only exist on laser turret, not railgun turret. Both laser and railgun render correctly on ship with this commit. I do not understand which code could break laser turret addon. And are you gonna put this new VS compatible version on curse? I'm considering ask people make videos with VS ships mount with OMT turrets

**Comment by Keridos** [comment]
Yeah, gonna upload that once VS is put back on daporkchops maven (no need to tell him, I already chatted about that with him). Once that is complete travis should work again, too.

**Comment by Sunspot0411** [comment]
Sounds good! Just don't forget to merge this commit before curse release

**Comment by Sunspot0411** [comment]
@Keridos Why is this still not merged with the 3.1.x branch? You really don't need VS on maven because this fix only needs VW API, which is on maven all the time.

**Comment by Keridos** [comment]
Real Life and holidays...
Might find the time for that in mid january

**Pull request closed without merging**
