### PR TITLE
fixed Valkyrien Warfare mod compatibily

### PR DESCRIPTION
**Pull request by Sunspot0411**
Turrets now work on vw ships.

### CODE REVIEW

**Comment by Keridos** [comment]
Why did you delete the testImplementation in the build.gradle
It requires gradle 4.6 and as far as I know our wrapper is above that version? Other than that is looks fine.

**Comment by Keridos** [comment]
Eh @Sunspot0411 you still there?

**Comment by Sunspot0411** [comment]
sorry for the late reply. I deleted that because it would prevent me from setting up the dev environment on my computer

**Comment by Keridos** [comment]
Well and it does also kill the unit tests ensuring that most of our utility function work properly.

/edit If you did not get what I said, please add a commit that adds that back in.

**Comment by Sunspot0411** [comment]
I forgot where should testImplementation be in build.gradle file since it was a long time ago, would you tell me how to add it back?

**Comment by Keridos** [comment]
Just add the line back in you deleted o.O See your commit in here.

/edit: and for the future, please just comment out lines, that prevents messes like this.

**Comment by Sunspot0411** [comment]
@Keridos finally I got some time and add test implementation back. I believe you can merge branch now

**Comment by Sunspot0411** [comment]
@Keridos why this pull request is still not merged? I have fixed test build in build.gradle

**Comment by Keridos** [comment]
Ok, looks better, but the last commit has nothing to do with vw compatability, please remove that commit. I'll merge it then.

**Comment by Sunspot0411** [comment]
last commit may have nothing to do with vw, but i don't want railgun turrets to destroy blocks with hardness level greater than 200, because I don't want railgun turrets able to destroy armor blocks of my plasma cannon mod. If they can destroy armor blocks people won't need to build plasma cannons if they install both omt and plasma cannon mod

**Comment by Sunspot0411** [comment]
> Ok, looks better, but the last commit has nothing to do with vw compatability, please remove that commit. I'll merge it then.

i only limit hardness level large than 200. i'm sure 99.9999 percent blocks do not have values higher than this  so it does not affect game play at all if plasma cannon is not installed. for the sake of my mod, please keep the last commit. just think that as plasma cannon compatibility

**Comment by Keridos** [comment]
You can always put that in a different PR and I'd like the value to be configurable. Though it doesnt really matter atm, gonna release that for 1.12 anyway,

**Comment by Sunspot0411** [comment]
Thanks!

**Comment by Sunspot0411** [comment]
and by the way, would you allow me post this vw compatible omt on some other minecraft web page like mcbbs?

**Pull request merged**
