### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by NealDeal34**

### CODE REVIEW

**Comment by Keridos** [comment]
Sorry for that, but we now require a CLA before merging content. @bombcar @mitchej123 @ghostflyby @eigenraven 
Please accept the CLA

**Comment by mitchej123** [comment]
@Keridos I believe they opened a PR against upstream instead of our 1.7.10 fork by accident (Github is very annoying with the default behavior on this), apologies!

That being said, if you still care about patches for 1.7.10 we're happy to contribute, otherwise we're happy to continue maintaining our own fork.

**Comment by Keridos** [comment]
> @Keridos I believe they opened a PR against upstream instead of our 1.7.10 fork by accident (Github is very annoying with the default behavior on this), apologies!
> 
> That being said, if you still care about patches for 1.7.10 we're happy to contribute, otherwise we're happy to continue maintaining our own fork.

I noticed your fork has a working building script. I'd be happy to merge your changes in to the official repo. But I cannot enable CLA assistant to work only on the 1.19.2 branch, where we want it to apply too.

You may have also noticed I made a PR on your fork. I am currently playing GTNH and found the 1.7.10 version of OMT to be lacking quite a few QoL Features.

**Comment by mitchej123** [comment]
More than happy to - just signed it.  And now that you mention it, just saw the PR on our fork :+1:

**Pull request merged**
